# MTG Automotora - Cloudflare Pages Configuration

name = "mtg-automotora"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = ".vercel/output/static"

# Base de datos D1
[[d1_databases]]
binding = "DB"
database_name = "bdmtgzhipu"
database_id = "4f466d12-b23e-48da-921b-f74e334296d0"

# Bucket R2
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "mtgzhipu-files"

[vars]
ENVIRONMENT = "production"

[dev]
port = 3000
local_protocol = "http"
