name = "mtg-api"
main = "index.js"
compatibility_date = "2024-12-01"

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "bdmtgzhipu"
database_id = "4f466d12-b23e-48da-921b-f74e334296d0"

# R2 Bucket
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "mtgzhipu-files"

# Variables
[vars]
ENVIRONMENT = "production"
